events {}

http {
    upstream backend_servers {
        server web-server-1:80;
        server web-server-2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
        }
    }
}
